// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: v1/patrol.proto

package patrolv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/npclaudiu/patrol/engine/patrold/internal/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// EngineServiceName is the fully-qualified name of the EngineService service.
	EngineServiceName = "patrol.v1.EngineService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EngineServicePingProcedure is the fully-qualified name of the EngineService's Ping RPC.
	EngineServicePingProcedure = "/patrol.v1.EngineService/Ping"
)

// EngineServiceClient is a client for the patrol.v1.EngineService service.
type EngineServiceClient interface {
	Ping(context.Context, *connect.Request[v1.PingRequest]) (*connect.Response[v1.PingResponse], error)
}

// NewEngineServiceClient constructs a client for the patrol.v1.EngineService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEngineServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EngineServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	engineServiceMethods := v1.File_v1_patrol_proto.Services().ByName("EngineService").Methods()
	return &engineServiceClient{
		ping: connect.NewClient[v1.PingRequest, v1.PingResponse](
			httpClient,
			baseURL+EngineServicePingProcedure,
			connect.WithSchema(engineServiceMethods.ByName("Ping")),
			connect.WithClientOptions(opts...),
		),
	}
}

// engineServiceClient implements EngineServiceClient.
type engineServiceClient struct {
	ping *connect.Client[v1.PingRequest, v1.PingResponse]
}

// Ping calls patrol.v1.EngineService.Ping.
func (c *engineServiceClient) Ping(ctx context.Context, req *connect.Request[v1.PingRequest]) (*connect.Response[v1.PingResponse], error) {
	return c.ping.CallUnary(ctx, req)
}

// EngineServiceHandler is an implementation of the patrol.v1.EngineService service.
type EngineServiceHandler interface {
	Ping(context.Context, *connect.Request[v1.PingRequest]) (*connect.Response[v1.PingResponse], error)
}

// NewEngineServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEngineServiceHandler(svc EngineServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	engineServiceMethods := v1.File_v1_patrol_proto.Services().ByName("EngineService").Methods()
	engineServicePingHandler := connect.NewUnaryHandler(
		EngineServicePingProcedure,
		svc.Ping,
		connect.WithSchema(engineServiceMethods.ByName("Ping")),
		connect.WithHandlerOptions(opts...),
	)
	return "/patrol.v1.EngineService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EngineServicePingProcedure:
			engineServicePingHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEngineServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedEngineServiceHandler struct{}

func (UnimplementedEngineServiceHandler) Ping(context.Context, *connect.Request[v1.PingRequest]) (*connect.Response[v1.PingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("patrol.v1.EngineService.Ping is not implemented"))
}
